name: Bug Report
description: Something is broken
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Clear description of the bug
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Commands or code to trigger the bug
      value: |
        ```bash
        safeshift run ...
        ```
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: SafeShift version
      placeholder: "0.1.0"
  - type: input
    id: python
    attributes:
      label: Python version
      placeholder: "3.12"
